# Generated by Django 5.2.4 on 2025-07-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="ideas/%Y%m%d", verbose_name="이미지"
                    ),
                ),
                (
                    "interest",
                    models.PositiveIntegerField(default=0, verbose_name="관심도"),
                ),
                ("content", models.TextField(verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="수정일"),
                ),
                (
                    "devtool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.tool",
                        verbose_name="개발툴",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdeaStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ideas.idea"
                    ),
                ),
            ],
        ),
    ]
