# Generated by Django 5.2.4 on 2025-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="툴이름"),
                ),
                ("kind", models.CharField(max_length=50, verbose_name="툴타입")),
                ("content", models.TextField(verbose_name="툴설명")),
            ],
        ),
    ]
