from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    caption = models.TextField()
    image = models.ImageField(upload_to='posts/%Y%m%d',blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def like_count(self):
        return self.likes.count() # like_set : all Like objects related to this Post (auto-generated by Django)
    
    def comment_count(self):
        return self.comments.count()
    
    def __str__(self):
        return f'{self.user.username} post'
    
class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user','post') # one like per user per post

    def __str__(self):
        return f'{self.user.username} liked {self.post.id}'

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.user.username} commented on {self.post.id}'
