# Generated by Django 5.2.4 on 2025-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("year", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=32)),
                ("review_star", models.FloatField()),
                ("director", models.CharField(max_length=32)),
                ("actors", models.CharField(max_length=32)),
                ("running_time", models.CharField(max_length=20)),
                ("content", models.TextField()),
            ],
        ),
    ]
