# Generated by Django 5.2.4 on 2025-07-11 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_review_running_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="content",
            new_name="review_text",
        ),
    ]
