# Generated by Django 5.2.4 on 2025-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_rename_content_review_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "액션"),
                    ("drama", "드라마"),
                    ("comedy", "코미디"),
                    ("sf", "SF"),
                    ("thriller", "스릴러"),
                    ("romance", "로맨스"),
                    ("animation", "애니메이션"),
                    ("documentary", "다큐멘터리"),
                    ("fantasy", "판타지"),
                ],
                max_length=32,
            ),
        ),
    ]
