# Generated by Django 5.2.4 on 2025-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "액션"),
                    ("Drama", "드라마"),
                    ("Comedy", "코미디"),
                    ("SF", "SF"),
                    ("Thriller", "스릴러"),
                    ("Romance", "로맨스"),
                    ("Animation", "애니메이션"),
                    ("Documentary", "다큐멘터리"),
                    ("Fantasy", "판타지"),
                ],
                max_length=32,
            ),
        ),
    ]
