# Generated by Django 5.2.4 on 2025-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_comment_post_alter_like_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default="No content"),
            preserve_default=False,
        ),
    ]
